# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pénzügyi Tanács
tagline:          'Pénzügyi fogyasztóvédelmi tanácsadás'
description:      'Célunk, hogy segítsük a lakosságot a  pénzügyi vállalkozásokkal, szolgáltatókkal szemben felmerülő  vitás ügyek megoldásában, tanácsot adjunk  pénzügyi döntéseikben, pénzügyi tudatosságuk fejlesztésében.'
url:              http://penzugyitanacs.eu
baseurl:          /

author:
  name:           'Tavosz'
  url:            https://tavosz.hu

paginate:         5

# Custom vars
version:          2.1.0
