# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pénzügyi Tanács
tagline:          'Pénzügyi fogyasztóvédelmi tanácsadás'
description:      'Díjmentes - pártatlan – független pénzügyi fogyasztóvédelmi tanácsadás, tájékoztatás'
url:              http://penzugyitanacs.eu
baseurl:          /

author:
  name:           'Tavosz'
  url:            https://tavosz.hu

paginate:         5

# Custom vars
version:          2.1.0
